<div class="fb-like" data-href="https://www.dominio.com.br" data-width="200px" data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="false"></div>

<div class="fb-share-button" data-href="https://www.dominio.com.br/" data-layout="button_count" data-size="large" data-mobile-iframe="true">
	<a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.dominio.com.br%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Compartilhar</a>
</div>

<a href="https://twitter.com/nomePagina?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-size="large" data-lang="pt" data-show-count="false">Follow</a>

<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-size="large" data-text="texto" data-url="https://www.dominio.com.br" data-via="nomeEmpresaSite" data-hashtags="hashtag1, hashtag1" data-related="nomePaginaRelacionada1,nomePaginaRelacionada2" data-lang="pt" data-show-count="false">Tweet</a>
