        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <meta property="og:title" <?php echo 'content="' . $this->getFacebookTags('ogTitle') . '"'; ?>/>
        <meta property="og:description" <?php echo 'content="' . $this->getFacebookTags('ogDescription') . '"'; ?>/>
        <meta property="og:url" <?php echo 'content="' . $this->getFacebookTags('ogUrl') . '"'; ?>/>
        <meta property="og:image" <?php echo 'content="' . $this->getFacebookTags('ogImage') . '"'; ?>/>
        <meta property="og:image:type" content="image/png">
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="630">
        <meta property="og:type" content="website" />
        <meta property="og:locale" content="pt_BR">
        <meta property="fb:app_id" content="587028504979737">
        <meta property="og:site_name" content="Nome do Site" />
        <title><?php echo $this->getPageTitle(''); ?></title>
        <link rel="canonical" <?php echo 'href="' . $this->getCanonicalUrl() . '"'; ?>/>
        <link type="text/plain" rel="author" href="humans.txt" />
        <meta name="google-site-verification" content="Codigo Google" />
        <meta name="robots" <?php echo 'content="' . $this->getGoogleFollowTag() . '"'; ?> />
		    <meta name="msvalidate.01" content="Codigo Bing" />
        <!--[if IE]><link rel="shortcut icon" href="favicon_32x32.ico?v=2"><![endif]-->
        <link rel="icon" href="/public/favicon_16x16.png" sizes="16x16" />
        <link rel="icon" href="/public/favicon_24x24.png" sizes="24x24" />
        <link rel="icon" href="/public/favicon_32x32.png" sizes="32x32" />
        <link rel="icon" href="/public/favicon_48x48.png" sizes="48x48" />
        <link rel="icon" href="/public/favicon_64x64.png" sizes="64x64" />
        <link rel="icon" href="/public/favicon_128x128.png" sizes="128x128" />
        <link rel="apple-touch-icon" sizes="152x152" href="/public/apple_touch_icon_152x152.png" />
        <link rel="apple-touch-icon" sizes="144x144" href="/public/apple_touch_icon_144x144.png" />
        <link rel="apple-touch-icon" sizes="120x120" href="/public/apple_touch_icon_120x120.png" />
        <link rel="apple-touch-icon" sizes="114x114" href="/public/apple_touch_icon_114x114.png" />
        <link rel="apple-touch-icon" sizes="76x76" href="/public/apple_touch_icon_76x76.png" />
        <link rel="apple-touch-icon" sizes="72x72" href="/public/apple_touch_icon_72x72.png" />
        <link rel="apple-touch-icon" href="/public/apple_touch_icon_57x57.png" />
        <meta name="msapplication-TileImage" content="tile_144x144.png" />
        <meta name="msapplication-TileColor" content="#f15574" />
        <meta name="msapplication-tooltip" content="Descrição do tooltip" />
        <meta name="description" content="Descrição do site" />
        <meta name="keywords" content="Palavras Chaves" />
        <meta name="copyright" content="Nome Empresa/Site, Copyright (c) 2018" />
        <link rel="stylesheet" href="/public/assets/css/fontawesome-5.2.0.min.css">
        <link rel="stylesheet" href="/public/assets/css/bootstrap-4.1.3.min.css">
        <link rel="stylesheet" href="/public/assets/css/main.css">
        <script src="/public/assets/js/jquery-3.3.1.min.js"></script>
        <script src="/public/assets/js/bootstrap-4.1.3.min.js"></script>
        <script src="/public/assets/js/main.js"></script>
        <!-- Inicio Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=CodigoGoogle"></script>
        <script type="text/javascript">
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'CodigoGoogle');
        </script>
        <!-- Fim Global site tag (gtag.js) - Google Analytics -->
        <style type="text/css">
        </style>
